"""initial schema

Revision ID: 8facbe638ebc
Revises: 
Create Date: 2026-09-19 22:30:48.690085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8facbe638ebc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('requested_operation', sa.JSON(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('actor_type', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Text(), nullable=True),
    sa.CheckConstraint("decision in ('approved','rejected','expired')", name='ck_approval_log_decision'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Text(), nullable=False),
    sa.Column('availability', sa.Text(), nullable=False),
    sa.Column('parent_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('decision_at', sa.Text(), nullable=True),
    sa.CheckConstraint("availability in ('complete','incomplete')", name='ck_artifact_availability'),
    sa.CheckConstraint("decision in ('undecided','accepted','rejected')", name='ck_artifact_decision'),
    sa.ForeignKeyConstraint(['job_id'], ['generation_job.id'], ),
    sa.ForeignKeyConstraint(['parent_artifact_id'], ['artifact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('scene_ref', sa.JSON(), nullable=False),
    sa.Column('shot_ref', sa.JSON(), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('manifest_id', sa.String(length=36), nullable=False),
    sa.Column('parent_job_id', sa.String(length=36), nullable=True),
    sa.Column('queue_sequence', sa.Integer(), nullable=False),
    sa.Column('cancel_requested_at', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.Text(), nullable=True),
    sa.Column('failure_code', sa.Text(), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.CheckConstraint("kind in ('image','video','voice','music','compose')", name='ck_generation_job_kind'),
    sa.CheckConstraint("state in ('queued','running','cancelling','succeeded','failed','cancelled')", name='ck_generation_job_state'),
    sa.ForeignKeyConstraint(['manifest_id'], ['generation_manifest.id'], name='fk_generation_job_manifest_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['parent_job_id'], ['generation_job.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_manifest',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('engine', sa.Text(), nullable=False),
    sa.Column('engine_version', sa.Text(), nullable=False),
    sa.Column('model', sa.JSON(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('resolved_prompt', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('input_refs', sa.JSON(), nullable=False),
    sa.Column('workflow_artifact_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_job.id'], name='fk_generation_manifest_job_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['workflow_artifact_id'], ['artifact.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('engine', sa.Text(), nullable=False),
    sa.Column('workflow_template_ref', sa.JSON(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('defaults', sa.JSON(), nullable=False),
    sa.Column('supersedes_recipe_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    op.drop_table('generation_manifest')
    op.drop_table('generation_job')
    op.drop_table('artifact')
    op.drop_table('approval_log')
    # ### end Alembic commands ###
