/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/approval-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Approval Log */
        post: operations["create_approval_log_api_v1_approval_logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approval-logs/{approval_log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Approval Log */
        get: operations["get_approval_log_api_v1_approval_logs__approval_log_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Artifact */
        post: operations["create_artifact_api_v1_artifacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_v1_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact Content
         * @description Artifactの実ファイルを配信する。候補比較のプレビューに使う。
         *
         *     画面へ渡すのは`artifact_id`だけとし、保存先の絶対パスを外へ出さない。パスの解決は
         *     `storage`へ閉じ、`data_root`の外は配信しない。
         */
        get: operations["get_artifact_content_api_v1_artifacts__artifact_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Artifact Decision
         * @description 生成候補の採否を記録する。`undecided`へ戻すと判断時刻も消す。
         */
        patch: operations["update_artifact_decision_api_v1_artifacts__artifact_id__decision_patch"];
        trace?: never;
    };
    "/api/v1/generation-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Generation Jobs
         * @description キュー状態の確認用。既定はqueue_sequence昇順、指定した条件で絞り込む。
         *
         *     `scene_id`と`shot_id`は`scene_ref`/`shot_ref`の`id`と突き合わせる。画面が特定の
         *     Shotの生成履歴だけを見るために使う。
         */
        get: operations["list_generation_jobs_api_v1_generation_jobs_get"];
        put?: never;
        /**
         * Create Generation Job
         * @description RecipeからWorkflowを組み立て、JobとManifestのIDを先行採番して作成する。
         *
         *     JobとManifestは相互参照するため、同一トランザクションで相互参照ごと作成する。
         *     実行時Workflow JSONは先にArtifact storeへ書き出し、その内容のSHA-256を
         *     Workflow Artifactとして記録する。投入するのはこのファイルそのものとする。
         */
        post: operations["create_generation_job_api_v1_generation_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generation-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Generation Job */
        get: operations["get_generation_job_api_v1_generation_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generation-jobs/{job_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Job Artifacts
         * @description Jobに紐付くArtifactを作成順に返す。Workflowスナップショットも含む。
         */
        get: operations["list_job_artifacts_api_v1_generation_jobs__job_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generation-jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Generation Job
         * @description queuedは即cancelled、runningはcancellingへ遷移しExecutorへ取消を伝える。
         *
         *     条件付きUPDATEでワーカーの`_claim_next`/`_finalize`との競合を検知する。
         *     更新0件は他プロセスが先に状態を変えたことを意味し、409で再取得を促す。
         *     cancellingへの二重要求はidempotentに現在の状態を返す。
         */
        post: operations["cancel_generation_job_api_v1_generation_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generation-manifests/{manifest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Generation Manifest */
        get: operations["get_generation_manifest_api_v1_generation_manifests__manifest_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenes */
        get: operations["list_scenes_api_v1_projects__project_id__scenes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/scenes/{scene_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scene */
        get: operations["get_scene_api_v1_projects__project_id__scenes__scene_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/scenes/{scene_id}/shots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shots */
        get: operations["list_shots_api_v1_projects__project_id__scenes__scene_id__shots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/scenes/{scene_id}/shots/{shot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shot */
        get: operations["get_shot_api_v1_projects__project_id__scenes__scene_id__shots__shot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recipes
         * @description 画面のプリセット選択用。
         *
         *     Recipeは作成後に書き換えず、更新時は`supersedes_recipe_id`で後継を作る。既定では
         *     後継に置き換えられたRecipeを除き、選択肢に古い版が並ばないようにする。
         */
        get: operations["list_recipes_api_v1_recipes_get"];
        put?: never;
        /** Create Recipe */
        post: operations["create_recipe_api_v1_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe */
        get: operations["get_recipe_api_v1_recipes__recipe_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalLogCreate */
        ApprovalLogCreate: {
            /** Actor Id */
            actor_id: string;
            /** Actor Type */
            actor_type: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected" | "expired";
            /** Expires At */
            expires_at?: string | null;
            /** Requested Operation */
            requested_operation: {
                [key: string]: unknown;
            };
            /** Subject Id */
            subject_id: string;
            /** Subject Type */
            subject_type: string;
        };
        /** ApprovalLogRead */
        ApprovalLogRead: {
            /** Actor Id */
            actor_id: string;
            /** Actor Type */
            actor_type: string;
            /** Decided At */
            decided_at: string;
            /** Decision */
            decision: string;
            /** Expires At */
            expires_at: string | null;
            /** Id */
            id: string;
            /** Requested Operation */
            requested_operation: {
                [key: string]: unknown;
            };
            /** Subject Id */
            subject_id: string;
            /** Subject Type */
            subject_type: string;
        };
        /** ArtifactCreate */
        ArtifactCreate: {
            /**
             * Availability
             * @enum {string}
             */
            availability: "complete" | "incomplete";
            /** Byte Size */
            byte_size: number;
            /** Job Id */
            job_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "image" | "video" | "audio" | "workflow" | "log";
            /** Media Type */
            media_type: string;
            /** Parent Artifact Id */
            parent_artifact_id?: string | null;
            /** Relative Path */
            relative_path: string;
            /** Sha256 */
            sha256: string;
        };
        /**
         * ArtifactDecisionUpdate
         * @description 候補比較での採否。`undecided`へ戻すこともできる。
         */
        ArtifactDecisionUpdate: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "undecided" | "accepted" | "rejected";
        };
        /** ArtifactRead */
        ArtifactRead: {
            /** Availability */
            availability: string;
            /** Byte Size */
            byte_size: number;
            /** Created At */
            created_at: string;
            /** Decision */
            decision: string;
            /** Decision At */
            decision_at: string | null;
            /** Id */
            id: string;
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string;
            /** Media Type */
            media_type: string;
            /** Parent Artifact Id */
            parent_artifact_id: string | null;
            /** Relative Path */
            relative_path: string;
            /** Sha256 */
            sha256: string;
        };
        /**
         * GenerationJobCreate
         * @description Jobと実行時Manifestを同一トランザクションで作成する要求。
         *
         *     Workflow JSONはApplication APIがRecipeと`inputs`から組み立てる。呼び出し元は
         *     Manifestの中身もComfyUIのノードも組み立てない。
         */
        GenerationJobCreate: {
            /** Input Refs */
            input_refs?: {
                [key: string]: unknown;
            }[];
            /** Inputs */
            inputs?: {
                [key: string]: unknown;
            };
            /**
             * Kind
             * @enum {string}
             */
            kind: "image" | "video" | "voice" | "music" | "compose";
            /** Parent Job Id */
            parent_job_id?: string | null;
            /** Queue Sequence */
            queue_sequence: number;
            /** Recipe Id */
            recipe_id: string;
            /** Scene Ref */
            scene_ref: {
                [key: string]: unknown;
            };
            /** Shot Ref */
            shot_ref: {
                [key: string]: unknown;
            };
        };
        /** GenerationJobRead */
        GenerationJobRead: {
            /** Cancel Requested At */
            cancel_requested_at: string | null;
            /** Failure Code */
            failure_code: string | null;
            /** Failure Message */
            failure_message: string | null;
            /** Failure Stage */
            failure_stage: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Manifest Id */
            manifest_id: string;
            /** Parent Job Id */
            parent_job_id: string | null;
            /** Queue Sequence */
            queue_sequence: number;
            /** Recipe Id */
            recipe_id: string;
            /** Retryable */
            retryable: boolean | null;
            /** Scene Ref */
            scene_ref: {
                [key: string]: unknown;
            };
            /** Shot Ref */
            shot_ref: {
                [key: string]: unknown;
            };
            /** Started At */
            started_at: string | null;
            /** State */
            state: string;
        };
        /** GenerationManifestRead */
        GenerationManifestRead: {
            /** Created At */
            created_at: string;
            /** Engine */
            engine: string;
            /** Engine Version */
            engine_version: string | null;
            /** Id */
            id: string;
            /** Input Refs */
            input_refs: {
                [key: string]: unknown;
            }[];
            /** Job Id */
            job_id: string;
            /** Model */
            model: {
                [key: string]: unknown;
            };
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Resolved Prompt */
            resolved_prompt: string;
            /** Seed */
            seed: number;
            /** Workflow Artifact Id */
            workflow_artifact_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RecipeCreate */
        RecipeCreate: {
            /** Defaults */
            defaults: {
                [key: string]: unknown;
            };
            /** Engine */
            engine: string;
            /** Input Schema */
            input_schema: {
                [key: string]: unknown;
            };
            /**
             * Kind
             * @enum {string}
             */
            kind: "image" | "video" | "voice" | "music" | "compose";
            /** Name */
            name: string;
            /** Supersedes Recipe Id */
            supersedes_recipe_id?: string | null;
            /** Workflow Template Ref */
            workflow_template_ref: {
                [key: string]: unknown;
            };
        };
        /** RecipeRead */
        RecipeRead: {
            /** Created At */
            created_at: string;
            /** Defaults */
            defaults: {
                [key: string]: unknown;
            };
            /** Engine */
            engine: string;
            /** Id */
            id: string;
            /** Input Schema */
            input_schema: {
                [key: string]: unknown;
            };
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Supersedes Recipe Id */
            supersedes_recipe_id: string | null;
            /** Workflow Template Ref */
            workflow_template_ref: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_approval_log_api_v1_approval_logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approval_log_api_v1_approval_logs__approval_log_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_artifact_api_v1_artifacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_v1_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_content_api_v1_artifacts__artifact_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_artifact_decision_api_v1_artifacts__artifact_id__decision_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactDecisionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_generation_jobs_api_v1_generation_jobs_get: {
        parameters: {
            query?: {
                state?: ("queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled") | null;
                scene_id?: string | null;
                shot_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_generation_job_api_v1_generation_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generation_job_api_v1_generation_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_job_artifacts_api_v1_generation_jobs__job_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_generation_job_api_v1_generation_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generation_manifest_api_v1_generation_manifests__manifest_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manifest_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationManifestRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenes_api_v1_projects__project_id__scenes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scene_api_v1_projects__project_id__scenes__scene_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                scene_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shots_api_v1_projects__project_id__scenes__scene_id__shots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                scene_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shot_api_v1_projects__project_id__scenes__scene_id__shots__shot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                scene_id: string;
                shot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recipes_api_v1_recipes_get: {
        parameters: {
            query?: {
                kind?: ("image" | "video" | "voice" | "music" | "compose") | null;
                engine?: string | null;
                latest?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_recipe_api_v1_recipes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_api_v1_recipes__recipe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
